name: Vanish
main: com.angga7togk.Vanish
version: 1.0
api: 1.0.0
author: Angga7Togk
description: "Vanish Plugin By Angga7Togk"

permissions:
  vanish.command:
    default: op
  vanish.command.others:
    default: op
  vanish.see:
    default: op
  vanish.admin:
    default: op